MSG_NOT_WORKING = "The system is not working"
MSG_NOT_PARK_NOW = "You can not park now"
MSG_ALREADY_PARKED = "This vehicle is already parked"
MSG_NOT_ENOUGH_MONEY = "You do not have enough money to park"
MSG_VEHICLE_NOT_EXIST = "This vehicle does not exist"
MSG_VEHICLE_NOT_PARKED = "This vehicle is not parked"
