# Generated by Django 4.1.7 on 2023-03-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='minumum_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='negative_allowed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
