# Generated by Django 4.1.7 on 2023-03-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_is_working_company_minumum_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parked',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
