# Generated by Django 4.1.7 on 2023-03-20 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parked_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parked',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 5, 40, 0, 217773, tzinfo=datetime.timezone.utc)),
        ),
    ]
